spring:
  application.name: cloud-storage
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  session:
    timeout: 24h
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      enabled: true
      file-size-threshold: 2MB
  data:
    redis:
      host: redis
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-wait: 100ms
          max-idle: 8
          min-idle: 1
        shutdown-timeout: 100ms
server:
  tomcat:
    max-swallow-size: 20MB
    connection-timeout: 600000

app:
  cors:
    allowed-origins:
        - "http://158.255.1.254:3000"
        - "http://158.255.1.254:80"
        - "http://158.255.1.254"
        - "http://frontend:3000"
        - "http://frontend:80"
        - "http://frontend"
        - "http://localhost:3000"
        - "http://localhost:80"
        - "http://localhost"

minio:
  url: ${MINIO_URL}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}

logging:
  file:
    name: ./logs/application.log
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
